spring:
  application:
    name: department-service
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoint:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/